// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: anti_fraud.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AntiFraudRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId int64                  `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	SenderId      int64                  `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId    int64                  `protobuf:"varint,3,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AntiFraudRequest) Reset() {
	*x = AntiFraudRequest{}
	mi := &file_anti_fraud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntiFraudRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntiFraudRequest) ProtoMessage() {}

func (x *AntiFraudRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anti_fraud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntiFraudRequest.ProtoReflect.Descriptor instead.
func (*AntiFraudRequest) Descriptor() ([]byte, []int) {
	return file_anti_fraud_proto_rawDescGZIP(), []int{0}
}

func (x *AntiFraudRequest) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *AntiFraudRequest) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *AntiFraudRequest) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *AntiFraudRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type AntiFraudResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFraud       bool                   `protobuf:"varint,1,opt,name=is_fraud,json=isFraud,proto3" json:"is_fraud,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	TrancheId     int64                  `protobuf:"varint,3,opt,name=tranche_id,json=trancheId,proto3" json:"tranche_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AntiFraudResponse) Reset() {
	*x = AntiFraudResponse{}
	mi := &file_anti_fraud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntiFraudResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntiFraudResponse) ProtoMessage() {}

func (x *AntiFraudResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anti_fraud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntiFraudResponse.ProtoReflect.Descriptor instead.
func (*AntiFraudResponse) Descriptor() ([]byte, []int) {
	return file_anti_fraud_proto_rawDescGZIP(), []int{1}
}

func (x *AntiFraudResponse) GetIsFraud() bool {
	if x != nil {
		return x.IsFraud
	}
	return false
}

func (x *AntiFraudResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AntiFraudResponse) GetTrancheId() int64 {
	if x != nil {
		return x.TrancheId
	}
	return 0
}

var File_anti_fraud_proto protoreflect.FileDescriptor

const file_anti_fraud_proto_rawDesc = "" +
	"\n" +
	"\x10anti_fraud.proto\x12\x04grpc\"\x8f\x01\n" +
	"\x10AntiFraudRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x03R\rtransactionId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\x03R\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x03 \x01(\x03R\n" +
	"receiverId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\"e\n" +
	"\x11AntiFraudResponse\x12\x19\n" +
	"\bis_fraud\x18\x01 \x01(\bR\aisFraud\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"tranche_id\x18\x03 \x01(\x03R\ttrancheId2W\n" +
	"\x10AntiFraudService\x12C\n" +
	"\x10CheckTransaction\x12\x16.grpc.AntiFraudRequest\x1a\x17.grpc.AntiFraudResponseB\x1eZ\x1cB-Wallet/anti_fraud/pkg/grpcb\x06proto3"

var (
	file_anti_fraud_proto_rawDescOnce sync.Once
	file_anti_fraud_proto_rawDescData []byte
)

func file_anti_fraud_proto_rawDescGZIP() []byte {
	file_anti_fraud_proto_rawDescOnce.Do(func() {
		file_anti_fraud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anti_fraud_proto_rawDesc), len(file_anti_fraud_proto_rawDesc)))
	})
	return file_anti_fraud_proto_rawDescData
}

var file_anti_fraud_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_anti_fraud_proto_goTypes = []any{
	(*AntiFraudRequest)(nil),  // 0: grpc.AntiFraudRequest
	(*AntiFraudResponse)(nil), // 1: grpc.AntiFraudResponse
}
var file_anti_fraud_proto_depIdxs = []int32{
	0, // 0: grpc.AntiFraudService.CheckTransaction:input_type -> grpc.AntiFraudRequest
	1, // 1: grpc.AntiFraudService.CheckTransaction:output_type -> grpc.AntiFraudResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_anti_fraud_proto_init() }
func file_anti_fraud_proto_init() {
	if File_anti_fraud_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anti_fraud_proto_rawDesc), len(file_anti_fraud_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_anti_fraud_proto_goTypes,
		DependencyIndexes: file_anti_fraud_proto_depIdxs,
		MessageInfos:      file_anti_fraud_proto_msgTypes,
	}.Build()
	File_anti_fraud_proto = out.File
	file_anti_fraud_proto_goTypes = nil
	file_anti_fraud_proto_depIdxs = nil
}
