// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: anti_fraud.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AntiFraudService_CheckTransaction_FullMethodName = "/grpc.AntiFraudService/CheckTransaction"
)

// AntiFraudServiceClient is the client API for AntiFraudService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AntiFraudServiceClient interface {
	CheckTransaction(ctx context.Context, in *AntiFraudRequest, opts ...grpc.CallOption) (*AntiFraudResponse, error)
}

type antiFraudServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAntiFraudServiceClient(cc grpc.ClientConnInterface) AntiFraudServiceClient {
	return &antiFraudServiceClient{cc}
}

func (c *antiFraudServiceClient) CheckTransaction(ctx context.Context, in *AntiFraudRequest, opts ...grpc.CallOption) (*AntiFraudResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AntiFraudResponse)
	err := c.cc.Invoke(ctx, AntiFraudService_CheckTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AntiFraudServiceServer is the server API for AntiFraudService service.
// All implementations must embed UnimplementedAntiFraudServiceServer
// for forward compatibility.
type AntiFraudServiceServer interface {
	CheckTransaction(context.Context, *AntiFraudRequest) (*AntiFraudResponse, error)
	mustEmbedUnimplementedAntiFraudServiceServer()
}

// UnimplementedAntiFraudServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAntiFraudServiceServer struct{}

func (UnimplementedAntiFraudServiceServer) CheckTransaction(context.Context, *AntiFraudRequest) (*AntiFraudResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckTransaction not implemented")
}
func (UnimplementedAntiFraudServiceServer) mustEmbedUnimplementedAntiFraudServiceServer() {}
func (UnimplementedAntiFraudServiceServer) testEmbeddedByValue()                          {}

// UnsafeAntiFraudServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AntiFraudServiceServer will
// result in compilation errors.
type UnsafeAntiFraudServiceServer interface {
	mustEmbedUnimplementedAntiFraudServiceServer()
}

func RegisterAntiFraudServiceServer(s grpc.ServiceRegistrar, srv AntiFraudServiceServer) {
	// If the following call pancis, it indicates UnimplementedAntiFraudServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AntiFraudService_ServiceDesc, srv)
}

func _AntiFraudService_CheckTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AntiFraudRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiFraudServiceServer).CheckTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiFraudService_CheckTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiFraudServiceServer).CheckTransaction(ctx, req.(*AntiFraudRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AntiFraudService_ServiceDesc is the grpc.ServiceDesc for AntiFraudService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AntiFraudService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.AntiFraudService",
	HandlerType: (*AntiFraudServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckTransaction",
			Handler:    _AntiFraudService_CheckTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "anti_fraud.proto",
}
